//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.05 at 06:12:29 PM IST 
//


package com.idbiintech.genFile;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.idbiintech.genFile package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.idbiintech.genFile
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest }
     * 
     */
    public OutwardRemittanceLodgeRequest createOutwardRemittanceLodgeRequest() {
        return new OutwardRemittanceLodgeRequest();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeResponse }
     * 
     */
    public OutwardRemittanceLodgeResponse createOutwardRemittanceLodgeResponse() {
        return new OutwardRemittanceLodgeResponse();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRq() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemChargeDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemChargeDtlsRemEntityChargeRec() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemTranDtlsRec() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsPurchaseSaleRec() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemDocumentDtlsRec }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemDocumentDtlsRec createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemDocumentDtlsRec() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemDocumentDtlsRec();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemMiscDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemPartyDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstrDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstrDtlsRemInstrDtlsRec() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqGeneralDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CustAddrDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CustAddrDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqGeneralDtlsCustAddrDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CustAddrDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeResponse.OutwardRemittanceLodgeRs }
     * 
     */
    public OutwardRemittanceLodgeResponse.OutwardRemittanceLodgeRs createOutwardRemittanceLodgeResponseOutwardRemittanceLodgeRs() {
        return new OutwardRemittanceLodgeResponse.OutwardRemittanceLodgeRs();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.CritDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.CritDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqCritDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.CritDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstructionDtlsRec }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstructionDtlsRec createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstructionDtlsRec() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstructionDtlsRec();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.CalculatedAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.CalculatedAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemChargeDtlsRemEntityChargeRecCalculatedAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.CalculatedAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeRate }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeRate createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemChargeDtlsRemEntityChargeRecChargeRate() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeRate();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeSplitPercent }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeSplitPercent createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemChargeDtlsRemEntityChargeRecChargeSplitPercent() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeSplitPercent();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeSplitAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeSplitAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemChargeDtlsRemEntityChargeRecChargeSplitAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemChargeDtls.RemEntityChargeRec.ChargeSplitAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TrnAcctId }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TrnAcctId createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemTranDtlsRecTrnAcctId() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TrnAcctId();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.RefAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.RefAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemTranDtlsRecRefAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.RefAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TreasuryRate }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TreasuryRate createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemTranDtlsRecTreasuryRate() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TreasuryRate();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.Rate }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.Rate createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemTranDtlsRecRate() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.Rate();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TrnAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TrnAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemTranDtlsRecTrnAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemTranDtlsRec.TrnAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.CustPrefInt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.CustPrefInt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsCustPrefInt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.CustPrefInt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.TrnTypeSubType }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.TrnTypeSubType createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsTrnTypeSubType() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.TrnTypeSubType();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.BillPrefInt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.BillPrefInt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsBillPrefInt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.BillPrefInt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.EventAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.EventAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsEventAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.EventAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTAcct }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTAcct createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsPurchaseSaleRecPSTAcct() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTAcct();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTRefAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTRefAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsPurchaseSaleRecPSTRefAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTRefAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTTreasuryRate }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTTreasuryRate createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsPurchaseSaleRecPSTTreasuryRate() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTTreasuryRate();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTRate }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTRate createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsPurchaseSaleRecPSTRate() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTRate();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTTrnAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTTrnAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemCurrEventDtlsBillEventDtlsPurchaseSaleRecPSTTrnAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemCurrEventDtls.BillEventDtls.PurchaseSaleRec.PSTTrnAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemDocumentDtlsRec.Amt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemDocumentDtlsRec.Amt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemDocumentDtlsRecAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemDocumentDtlsRec.Amt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls.EefcRate }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls.EefcRate createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemMiscDtlsEefcRate() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls.EefcRate();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls.EefcAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls.EefcAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemMiscDtlsEefcAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemMiscDtls.EefcAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.BenAddrDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.BenAddrDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemPartyDtlsBenAddrDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.BenAddrDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.BenefBankAddrDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.BenefBankAddrDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemPartyDtlsBenefBankAddrDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.BenefBankAddrDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.CorrespondentBankAddrDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.CorrespondentBankAddrDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemPartyDtlsCorrespondentBankAddrDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemPartyDtls.CorrespondentBankAddrDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.TotalInstrmntAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.TotalInstrmntAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstrDtlsTotalInstrmntAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.TotalInstrmntAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBranchDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBranchDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstrDtlsRemInstrDtlsRecDraweeBranchDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBranchDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBankDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBankDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstrDtlsRemInstrDtlsRecDraweeBankDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBankDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.InstrAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.InstrAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstrDtlsRemInstrDtlsRecInstrAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.InstrAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeAddrDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeAddrDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstrDtlsRemInstrDtlsRecDraweeAddrDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeAddrDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBankAddrDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBankAddrDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqRemInstrDtlsRemInstrDtlsRecDraweeBankAddrDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.RemInstrDtls.RemInstrDtlsRec.DraweeBankAddrDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.OperAcctId }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.OperAcctId createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqGeneralDtlsOperAcctId() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.OperAcctId();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.OperChrgAcctId }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.OperChrgAcctId createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqGeneralDtlsOperChrgAcctId() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.OperChrgAcctId();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.RemittanceAmt }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.RemittanceAmt createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqGeneralDtlsRemittanceAmt() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.RemittanceAmt();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CollBankAddrDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CollBankAddrDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqGeneralDtlsCollBankAddrDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CollBankAddrDtls();
    }

    /**
     * Create an instance of {@link OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CustAddrDtls.AddressDtls }
     * 
     */
    public OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CustAddrDtls.AddressDtls createOutwardRemittanceLodgeRequestOutwardRemittanceLodgeRqGeneralDtlsCustAddrDtlsAddressDtls() {
        return new OutwardRemittanceLodgeRequest.OutwardRemittanceLodgeRq.GeneralDtls.CustAddrDtls.AddressDtls();
    }

}
