//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.05 at 06:12:29 PM IST 
//


package com.idbiintech.genFile;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OutwardRemittanceLodgeRs"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="remittanceId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="OutwardRemittanceLodge_CustomData" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outwardRemittanceLodgeRs",
    "outwardRemittanceLodgeCustomData"
})
@XmlRootElement(name = "OutwardRemittanceLodgeResponse")
public class OutwardRemittanceLodgeResponse {

    @XmlElement(name = "OutwardRemittanceLodgeRs", required = true)
    protected OutwardRemittanceLodgeResponse.OutwardRemittanceLodgeRs outwardRemittanceLodgeRs;
    @XmlElement(name = "OutwardRemittanceLodge_CustomData", required = true)
    protected String outwardRemittanceLodgeCustomData;

    /**
     * Gets the value of the outwardRemittanceLodgeRs property.
     * 
     * @return
     *     possible object is
     *     {@link OutwardRemittanceLodgeResponse.OutwardRemittanceLodgeRs }
     *     
     */
    public OutwardRemittanceLodgeResponse.OutwardRemittanceLodgeRs getOutwardRemittanceLodgeRs() {
        return outwardRemittanceLodgeRs;
    }

    /**
     * Sets the value of the outwardRemittanceLodgeRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutwardRemittanceLodgeResponse.OutwardRemittanceLodgeRs }
     *     
     */
    public void setOutwardRemittanceLodgeRs(OutwardRemittanceLodgeResponse.OutwardRemittanceLodgeRs value) {
        this.outwardRemittanceLodgeRs = value;
    }

    /**
     * Gets the value of the outwardRemittanceLodgeCustomData property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutwardRemittanceLodgeCustomData() {
        return outwardRemittanceLodgeCustomData;
    }

    /**
     * Sets the value of the outwardRemittanceLodgeCustomData property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutwardRemittanceLodgeCustomData(String value) {
        this.outwardRemittanceLodgeCustomData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="remittanceId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "remittanceId"
    })
    public static class OutwardRemittanceLodgeRs {

        @XmlElement(required = true)
        protected String remittanceId;

        /**
         * Gets the value of the remittanceId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemittanceId() {
            return remittanceId;
        }

        /**
         * Sets the value of the remittanceId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemittanceId(String value) {
            this.remittanceId = value;
        }

    }

}
