//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.07.05 at 06:12:29 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://dcdmisapppr01.idbibank.com/14000/FISERVLET/fihttp", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.idbiintech.genFile;
